import { useCallback, useEffect, useState } from 'react';
import type { ArticleDraft, PublishRecord } from '../../shared/types';
import { api } from '../api';

interface Props {
  caseStudyId: string;
}

export function DraftsPage({ caseStudyId }: Props) {
  const [drafts, setDrafts] = useState<ArticleDraft[]>([]);
  const [active, setActive] = useState<ArticleDraft | null>(null);
  const [publishRecords, setPublishRecords] = useState<PublishRecord[]>([]);
  const [markdown, setMarkdown] = useState('');
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const refresh = useCallback(async () => {
    const { drafts } = await api.listDrafts(caseStudyId);
    setDrafts(drafts);
  }, [caseStudyId]);

  useEffect(() => {
    setActive(null);
    void refresh();
  }, [refresh]);

  const open = async (id: string) => {
    const { draft, publishRecords } = await api.getDraft(id);
    setActive(draft);
    setMarkdown(draft.markdown);
    setPublishRecords(publishRecords);
  };

  const generate = async () => {
    setBusy(true);
    setError(null);
    try {
      const { draft } = await api.generateDraft(caseStudyId);
      await refresh();
      await open(draft.id);
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
    } finally {
      setBusy(false);
    }
  };

  const save = async () => {
    if (!active) return;
    const { draft } = await api.updateDraft(active.id, { markdown });
    await refresh();
    await open(draft.id);
  };

  const publish = async () => {
    if (!active) return;
    setError(null);
    try {
      await api.publishDraft(active.id);
      await open(active.id);
      await refresh();
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
    }
  };

  const latestPublish = publishRecords.find((r) => r.status === 'published');

  return (
    <div>
      <div className="toolbar">
        <button className="primary" onClick={() => void generate()} disabled={busy}>
          {busy ? 'Generating…' : 'Generate draft'}
        </button>
        {drafts.map((d) => (
          <button
            key={d.id}
            className={d.id === active?.id ? 'active' : ''}
            onClick={() => void open(d.id)}
          >
            v{d.version} ({d.status})
          </button>
        ))}
      </div>

      {error && <p className="error">{error}</p>}

      {active && (
        <div className="panel">
          <h3>
            {active.title} — v{active.version}{' '}
            <span className="muted" style={{ fontSize: '0.8rem' }}>
              {active.provider ? `generated by ${active.provider}` : 'edited'}
            </span>
          </h3>
          <textarea
            className="article-editor"
            value={markdown}
            onChange={(e) => setMarkdown(e.target.value)}
          />
          <div className="toolbar" style={{ marginTop: '1rem', marginBottom: 0 }}>
            <button className="primary" onClick={() => void save()}>
              Save as new version
            </button>
            <a href={`/api/drafts/${active.id}/export`} download className="button-link">
              Export Markdown
            </a>
            <button onClick={() => void publish()}>Publish</button>
            {latestPublish && (
              <button
                className="danger"
                onClick={() =>
                  void api.unpublish(latestPublish.id).then(() => open(active.id))
                }
              >
                Unpublish
              </button>
            )}
          </div>
          {publishRecords.length > 0 && (
            <div style={{ marginTop: '1rem' }}>
              <p className="muted">Publish history</p>
              {publishRecords.map((r) => (
                <p key={r.id} className="muted" style={{ fontSize: '0.8rem', margin: '0.2rem 0' }}>
                  {r.status} → {r.path ?? r.error ?? ''}{' '}
                  {r.publishedAt ? `at ${r.publishedAt}` : ''}
                </p>
              ))}
            </div>
          )}
        </div>
      )}
    </div>
  );
}
